"""Add Review Model

Revision ID: 5473389a4771
Revises: c71d04fec7a2
Create Date: 2023-08-26 15:48:09.495056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5473389a4771'
down_revision = 'c71d04fec7a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
